name: Format, lint and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_tests:
    name: Install and check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.17"  # Update regularly

      - name: Make sure project is synced
        run: uv lock --check

      - name: Format check with ruff
        run: uv run ruff format --check

      - name: Linting check with ruff
        run: uv run ruff check
        
      - name: Install tkinter
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Test with pytest
        run: uv run pytest
